fairway/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^taskmonitor/', include('taskmonitor.urls', namespace="taskmonitor")),
    url(r'^admin/', include(admin.site.urls)),
]

taskmonitor/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

taskmonitor/models.py
from django.db import models
from django.utils.decorators import classonlymethod
from mptt.models import MPTTModel, TreeForeignKey
from mptt.managers import TreeManager

# TODO How to handle exception in Task.last_done_date()


class ComponentGroup(MPTTModel):
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    icon = models.CharField(max_length=100, null=True, blank=True)
    parent = TreeForeignKey('self', related_name='children', null=True, blank=True)
    tree = TreeManager()

    # @property
    def __str__(self):
        return self.name

    # def is_indirect_child(self, group):
    def is_sub_menu(self):
        return self.level == 1


class Component(ComponentGroup):
    manufacturer = models.CharField(max_length=100, null=True, blank=True)
    model = models.CharField(max_length=100, null=True, blank=True)


class Lifeboat(Component):
    capacity = models.PositiveSmallIntegerField()


class Task(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    interval = models.DurationField(blank=True, null=True)
    component_groups = models.ManyToManyField(ComponentGroup)

    def __str__(self):
        return self.name


class TaskLogEntry(models.Model):
    task = models.ForeignKey(Task)
    date = models.DateField()
    remark = models.TextField(null=True, blank=True)
    component_group = models.ForeignKey(ComponentGroup)

    def __str__(self):
        return self.component_group.name + ' / ' + self.task.name + ' / ' + str(self.date)

taskmonitor/views.py
from django.shortcuts import render
from django.views import generic
from taskmonitor.models import ComponentGroup
from django.http import Http404
import json

# Create your views here.
# Serialize Components Tree to JSON

def mptt_tree(root_nodes_queryset):

    tree =[]

    def loop(node):
        node_list = []
        for child in node.children.all() :
            node_dic = {'text': child.name}
            if not child.is_leaf_node():
                node_dic['nodes'] = loop(child)
            node_list.append(node_dic)
        return node_list
            
    for root in root_nodes_queryset:
        dic = {'text': root.name}
        if not root.is_leaf_node():
            dic['nodes'] = loop(root)
        tree.append(dic)

    return tree

def task_last_done_date(task, component_group):
    last_tasklog = component_group.tasklogentry_set.filter(task=task).order_by('date').first()
    try:
        return last_tasklog.date
    except AttributeError:
        return "Never"


def task_next_due_date(task, component_group):
    # FIXME Can't convert 'datetime.timedelta' object to str implicitly
    return task.last_done_date(component_group) + task.interval


def each_context():
    """
    Returns a dictionary of variables to put in the template context for
    *every* page in the site.
    """
    
    return {
            'nodes':ComponentGroup.tree.filter(level__lte=2)
            }



class IndexView(generic.ListView):
    model = ComponentGroup
    template_name = 'taskmonitor/base_taskmonitor.html'
    context_object_name = 'groups'

    def get_context_data(self, ** kwargs):
        context = super(IndexView, self).get_context_data(** kwargs)
        context.update(each_context())
        return context


def detail(request, pk):

    try:
        component_group = ComponentGroup.objects.get(pk=pk)
    except ComponentGroup.DoesNotExist:
        raise Http404("Component does not exist")

    context = {'componentgroup': component_group}
    context.update(each_context())

    tasks = []
    for group in component_group.get_ancestors(ascending=True, include_self=True):
        for task in group.task_set.all():
            task.last_done = task_last_done_date(task, group)
            # task.next_due = task.next_due_date(component_group)
            task.group = group
            tasks += [task]

    context.update({"tasks": tasks})

    return render(request, 'taskmonitor/taskmonitor_component_detail.html', context)

taskmonitor/templates/taskmonitor/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %} Fairway {% endblock %}</title>

    <!-- Bootstrap -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Custom Stylesheets -->
    <link rel="stylesheet" href="{% static "taskmonitor/css/responsive-nav-menu.css" %}">

  </head>

  <body>

    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

    <script>
      $('.no-collapsable').on('click', function (e) {
        e.stopPropagation();
      });
    </script>

  </body>

</html>

taskmonitor/templates/taskmonitor/base_taskmonitor.html
{% extends "taskmonitor/base.html" %}

{% load mptt_tags %}

{% block content %}

{% block component_tree_view %}
<div class="nav-side-menu">
  <div class="brand">Fairway</div>
  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  <div class="menu-list">

    <ul id="menu-content" class="menu-content collapse out">

      {% recursetree nodes %}

        <li data-toggle="collapse" data-target="#sub{{node.id}}" class="collapsed">
          <a href="{% url 'taskmonitor:detail' node.id %}" class="no-collapsable">
            {% if node.icon %}
              <i class="fa fa-lg {{node.icon}} "></i>
            {% endif %}
            {{node.name}}
          </a>
          {% if not node.is_leaf_node %}
            <span class="arrow"></span>
          {% endif %}
	</li>

        {% if not node.is_leaf_node %}
          {% if node.is_root_node %}
            <ul class="sub-menu collapse out" id="sub{{node.id}}">
          {% elif node.is_sub_menu %}
            <ul class="sub-sub-menu collapse out" id="sub{{node.id}}">
          {% endif %}
          {{ children }}
          </ul>
        {% endif %}

      {% endrecursetree %}

    </ul>

  </div>
</div>

{% endblock component_tree_view %}

{% block component_group_detail %}{% endblock component_group_detail %}

{% endblock content %}

taskmonitor/templates/taskmonitor/taskmonitor_component_detail.html
{% extends "taskmonitor/base_taskmonitor.html" %}

{% block component_group_detail %}
<div class="container">
<h2>{{ componentgroup.name }}</h2>

{% for task in tasks %}
<h3>{{task.group.name}} Tasks</h3>
<ul>
    <li>
    <h4>{{task.name}}</h4>
    <p>{{task.description}}</p>
    <p>{{task.interval}}</p>
    <p>{{task.last_done}}</p>
    <p>{{task.next_due}}</p>
    </li>
</ul>
{% endfor %}
</div>
{% endblock %}